# CivicPress pnpm Workspace Configuration
#
# This file defines the workspace structure for CivicPress.
# As the project grows, we can add packages here.

packages:
  # Core packages
  - 'packages/*'

  # Apps (when we add them)
  - 'apps/*'

  # Tools and utilities
  - 'tools/*'

  # Documentation
  - 'docs/*'

  # Examples
  - 'examples/*'

  # Root package (this directory)
  - '.'
