# CivicPress pnpm Workspace Configuration
#
# This file defines the workspace structure for CivicPress.
# As the project grows, we can add packages here.

packages:
  - 'core'
  - 'cli'
  - 'modules/*'
