# CivicPress pnpm Workspace Configuration
#
# This file defines the workspace structure for CivicPress.
# As the project grows, we can add packages here.

packages:
  - cli
  - core
  - modules/api
  - modules/ui
  - modules/legal-register
  - modules/realtime
  - modules/storage
  # - modules/serve (Astro frontend removed)
