name: 🐛 Bug Report
description: Report a bug or issue in CivicPress
labels: [bug, needs-triage]
assignees: []
title: '[BUG] '

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve CivicPress! 

        Before submitting, please:
        - Check existing issues to avoid duplicates
        - Try to reproduce the issue with the latest version
        - Include as much detail as possible
        - Consider the civic impact of this issue

  - type: input
    id: summary
    attributes:
      label: 🎯 Bug Summary
      description: A clear, concise description of the bug
      placeholder:
        'e.g., Legal register validation fails for certain record types'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Detailed Description
      description: What happened? What should have happened?
      placeholder: |
        **What happened:**
        When trying to validate a legal record with type "ordinance", the system throws an error...

        **What should have happened:**
        The validation should complete successfully and show a success message...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Navigate to the legal register module
        2. Create a new record with type "ordinance"
        3. Fill in the required fields
        4. Click "Validate Record"
        5. See error message
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What did you expect to happen?
      placeholder: |
        The validation should:
        - Complete without errors
        - Show a green success message
        - Allow the record to be saved
      render: markdown
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened?
      placeholder: |
        Instead, the system:
        - Throws a validation error
        - Shows red error message
        - Prevents record from being saved
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How critical is this issue?
      options:
        - '🔴 Critical - System crash or data loss'
        - '🟡 High - Major functionality broken'
        - '🟢 Medium - Minor functionality issue'
        - '🔵 Low - Cosmetic or minor inconvenience'
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📦 Version
      description: What version of CivicPress are you using?
      placeholder: '1.0.0 (or commit hash)'

  - type: dropdown
    id: environment
    attributes:
      label: 💻 Environment
      description: What's your setup?
      options:
        - '🖥️ Desktop - Windows'
        - '🖥️ Desktop - macOS'
        - '🖥️ Desktop - Linux'
        - '📱 Mobile - iOS'
        - '📱 Mobile - Android'
        - '🌐 Web Browser'
        - '🐳 Docker'
        - '☁️ Cloud Deployment'

  - type: textarea
    id: system
    attributes:
      label: 🔧 System Information
      description: OS, browser, Node.js version, etc.
      placeholder: |
        **Operating System:** macOS 14.0
        **Node.js Version:** 20.11.1
        **Browser:** Chrome 120.0
        **CivicPress Version:** 1.0.0
        **pnpm Version:** 10.12.4

  - type: textarea
    id: logs
    attributes:
      label: 📋 Error Logs
      description: Any error messages, console logs, or stack traces
      placeholder: |
        ```
        Error: Validation failed for record type 'ordinance'
        at LegalRegister.validateRecord (/modules/legal-register/index.js:45:12)
        at processRecord (/core/validation.js:23:8)
        ```

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Videos
      description: Visual evidence of the bug (if applicable)
      placeholder: |
        - Screenshot of the error message
        - Video showing the reproduction steps
        - Console output or logs

  - type: textarea
    id: civic-impact
    attributes:
      label: 🏛️ Civic Impact
      description: How does this bug affect civic operations or public trust?
      placeholder: |
        - Does this affect public record transparency?
        - Are citizens unable to access important information?
        - Does this impact government accountability?
        - Are there workarounds that maintain civic function?

  - type: textarea
    id: additional
    attributes:
      label: 📋 Additional Context
      description: Any other relevant information
      placeholder: |
        - When did this start happening?
        - Does it happen with all record types or just specific ones?
        - Any recent changes that might have caused this?
        - Workarounds you've found
        - Related issues or discussions

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Bug Report Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I've searched existing issues to avoid duplicates
        - label: I've tried to reproduce the issue with the latest version
        - label: I've included all relevant system information
        - label: I've provided clear steps to reproduce
        - label: I've included error logs or screenshots if applicable
        - label: I've considered the civic impact and public trust implications

  - type: markdown
    attributes:
      value: |
        ---

        **Thank you for helping make CivicPress more reliable and trustworthy!** 🛠️🏛️

        Our team will investigate this issue and respond within 1-2 weeks.
        For critical issues affecting public trust or civic operations, please tag maintainers immediately.
