version: 1.0.0
name: Civic Records
city: Richmond
state: Quebec
country: Canada
timezone: America/New_York
repo_url: null
modules:
  - legal-register
record_types:
  - bylaw
  - policy
default_role: clerk
hooks:
  enabled: true
workflows:
  enabled: true
audit:
  enabled: true
created: 2025-07-07T21:18:14.012Z
