/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical message catalog for the appliance↔CivicPress WebSocket contract. Greenfield (no legacy shapes). Every message is {type, id, timestamp, …}; envelopes are strict (additionalProperties:false). Consumed by both repos: the hardware client generates pydantic from this file; the server (Phase 5) generates TS types.
 */
export type CivicPressBroadcastBoxWireProtocol =
  | Command
  | Ack
  | Event
  | Status
  | Heartbeat
  | SchedulePush
  | SessionManifest
  | StreamConfigure
  | StreamStart
  | StreamStop
  | PreviewOffer
  | PreviewAnswer
  | PreviewIceCandidate
  | PreviewStopped
  | ConnectionAck
  | ReEnrolled
  | AuthFailed
  | Error;
/**
 * Message id (UUID recommended).
 */
export type Id = string;
/**
 * ISO 8601 timestamp.
 */
export type Timestamp = string;
export type Visibility = "public" | "in_camera";

/**
 * CP → device. Imperative action the device must execute.
 */
export interface Command {
  type: "command";
  id: Id;
  timestamp: Timestamp;
  action: string;
  payload?: {
    [k: string]: unknown;
  };
}
/**
 * device → CP. Acknowledges a command by id.
 */
export interface Ack {
  type: "ack";
  id: Id;
  timestamp: Timestamp;
  commandId: string;
  success: boolean;
  payload?: {
    [k: string]: unknown;
  };
  error?: string;
  errorCode?: string;
  errorType?: string;
  errorDetails?: {
    [k: string]: unknown;
  };
}
/**
 * device → CP. A named event (e.g. device.connected).
 */
export interface Event {
  type: "event";
  id: Id;
  timestamp: Timestamp;
  event: string;
  payload?: {
    [k: string]: unknown;
  };
}
/**
 * device → CP. Periodic status snapshot (also serves as keepalive).
 */
export interface Status {
  type: "status";
  id: Id;
  timestamp: Timestamp;
  payload: {
    [k: string]: unknown;
  };
}
/**
 * Either direction. Liveness ping.
 */
export interface Heartbeat {
  type: "heartbeat";
  id: Id;
  timestamp: Timestamp;
}
/**
 * CP → device. Upcoming sessions the device caches for offline-autonomous capture.
 */
export interface SchedulePush {
  type: "schedule.push";
  id: Id;
  timestamp: Timestamp;
  payload: {
    sessions: ScheduleItem[];
  };
}
export interface ScheduleItem {
  /**
   * Session record id.
   */
  id: string;
  scheduled_start: Timestamp;
  scheduled_end?: Timestamp;
  visibility?: Visibility;
  assigned_device?: string;
  agenda?: string[];
  [k: string]: unknown;
}
/**
 * device → CP. Binds an A/V upload to the session it belongs to.
 */
export interface SessionManifest {
  type: "session.manifest";
  id: Id;
  timestamp: Timestamp;
  payload: {
    session_id: string;
    capture: CaptureBlock;
  };
}
export interface CaptureBlock {
  device: string;
  av_file?: string;
  started_at?: Timestamp;
  ended_at?: Timestamp;
  duration_s?: number;
  segments?: Segment[];
  [k: string]: unknown;
}
export interface Segment {
  start: number;
  end: number;
  visibility: Visibility;
}
/**
 * CP → device. Configure the external RTMP restream target.
 */
export interface StreamConfigure {
  type: "stream.configure";
  id: Id;
  timestamp: Timestamp;
  payload: {
    platform: "youtube" | "facebook" | "twitch" | "generic";
    rtmp_url: string;
    /**
     * Secret — never logged; transported only over the control plane.
     */
    stream_key?: string;
  };
}
/**
 * CP → device. Begin the external restream.
 */
export interface StreamStart {
  type: "stream.start";
  id: Id;
  timestamp: Timestamp;
  payload?: {
    [k: string]: unknown;
  };
}
/**
 * CP → device. Stop the external restream.
 */
export interface StreamStop {
  type: "stream.stop";
  id: Id;
  timestamp: Timestamp;
  payload?: {
    [k: string]: unknown;
  };
}
/**
 * device → CP. WebRTC offer for the clerk monitoring preview.
 */
export interface PreviewOffer {
  type: "preview.offer";
  id: Id;
  timestamp: Timestamp;
  payload: {
    [k: string]: unknown;
  };
}
/**
 * CP → device. WebRTC answer.
 */
export interface PreviewAnswer {
  type: "preview.answer";
  id: Id;
  timestamp: Timestamp;
  payload: {
    [k: string]: unknown;
  };
}
/**
 * Either direction. WebRTC ICE candidate.
 */
export interface PreviewIceCandidate {
  type: "preview.ice_candidate";
  id: Id;
  timestamp: Timestamp;
  payload: {
    [k: string]: unknown;
  };
}
/**
 * device → CP. Preview stream ended.
 */
export interface PreviewStopped {
  type: "preview.stopped";
  id: Id;
  timestamp: Timestamp;
  payload?: {
    [k: string]: unknown;
  };
}
/**
 * CP → device. Connection accepted.
 */
export interface ConnectionAck {
  type: "connection.ack";
  id: Id;
  timestamp: Timestamp;
  payload?: {
    [k: string]: unknown;
  };
}
/**
 * CP → device. Device was re-enrolled; new credentials/endpoint apply.
 */
export interface ReEnrolled {
  type: "re_enrolled";
  id: Id;
  timestamp: Timestamp;
  payload?: {
    [k: string]: unknown;
  };
}
/**
 * CP → device. Authentication failed.
 */
export interface AuthFailed {
  type: "auth_failed";
  id: Id;
  timestamp: Timestamp;
  payload?: {
    [k: string]: unknown;
  };
}
/**
 * Either direction. Protocol-level error.
 */
export interface Error {
  type: "error";
  id: Id;
  timestamp: Timestamp;
  error?: string;
  errorCode?: string;
  payload?: {
    [k: string]: unknown;
  };
}
